cmake_minimum_required(VERSION 3.22.1)
project(pulso_tox LANGUAGES C CXX)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(SODIUM_DISABLE_TESTS ON CACHE BOOL "" FORCE)
add_subdirectory(vendor/sodium EXCLUDE_FROM_ALL)
add_library(libsodium::libsodium ALIAS sodium)
set(ENABLE_SHARED OFF CACHE BOOL "" FORCE)
set(ENABLE_STATIC ON CACHE BOOL "" FORCE)
set(BUILD_TOXAV OFF CACHE BOOL "" FORCE)
set(UNITTEST OFF CACHE BOOL "" FORCE)
set(AUTOTEST OFF CACHE BOOL "" FORCE)
set(DHT_BOOTSTRAP OFF CACHE BOOL "" FORCE)
set(BOOTSTRAP_DAEMON OFF CACHE BOOL "" FORCE)
set(MIN_LOGGER_LEVEL ERROR CACHE STRING "" FORCE)
add_subdirectory(vendor/toxcore EXCLUDE_FROM_ALL)
add_library(pulso_tox SHARED pulso_tox.cpp)
target_compile_features(pulso_tox PRIVATE cxx_std_17)
target_include_directories(pulso_tox PRIVATE vendor/toxcore)
target_link_libraries(pulso_tox PRIVATE toxcore_static)
target_link_options(pulso_tox PRIVATE "-Wl,-z,max-page-size=16384")
